### ISSUE TITLE
problemas de usabilidad

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#12]
![registro](https://github.com/user-attachments/assets/5852f5db-7bfc-4b79-bf8c-37c4de371abd)

no hay ningún tipo de navegabilidad

**Comment by danferkz** [comment]
ya se añadio la barra de navegacion:

![Captura de pantalla 2024-11-21 185432](https://github.com/user-attachments/assets/abed7771-6026-45ad-bdcd-492e70e43bfb)
