### ISSUE TITLE
Error al crear mueble

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#13]
![crear mueble](https://github.com/user-attachments/assets/9db9655a-ee12-4c0a-91f4-3e1ed0423dd2)
lo almacena en el backend pero no redirecciona ni se muestra en el listado de los pedidos de los usuarios

**Comment by danferkz** [comment]
Corregido el error.

![image](https://github.com/user-attachments/assets/71b2c7de-2b27-4d37-8c58-e31036d8819e)
