### ISSUE TITLE
error de interfaz

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#15]
![campos](https://github.com/user-attachments/assets/c0f15dec-6ddb-4278-9b61-5dcef68b74c6)
ningún campo tiene borde, lo que dificulta su localización a la hora de completar los datos

**Comment by danferkz** [comment]
Correccion de los campos de entrada con un borde y separacion de su contenido:
![image](https://github.com/user-attachments/assets/4b418d64-e9e7-4f7c-9a00-0ad95b502915)
