### ISSUE TITLE
Error de usabilidad

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#19]
![image](https://github.com/user-attachments/assets/a8964e1b-a49f-4467-bf1d-2657d34337fc)
para acceder al listado de pedidos del usuario hay que ir hasta su perfil, debería ser mucho más accesible, además no está listando los pedidos realizado aun cuando están almacenados en la bd

**Comment by danferkz** [comment]
ya funciona correctamente:
![image](https://github.com/user-attachments/assets/55520dbf-717f-416e-976d-40256889e4cc)
despues que haya ordenado un producto
![image](https://github.com/user-attachments/assets/d2ab5fd0-a8a7-4ee6-900f-99bdc0ba9460)
