### ISSUE TITLE
Fusionar

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#21]
![image](https://github.com/user-attachments/assets/4eaef116-2faa-4663-8130-1a89bbc235e8)
no debieran estar separadas las funcionalidades, un solo boton enviar que me calcule el precio y me realice el pedido, eso no es usable

**Comment by danferkz** [comment]
Se está utilizando de esta forma para facilitar que el usuario pueda ajustar los valores de personalización de su producto. Además, se añadieron validaciones en los campos, las cuales indican los campos faltantes. Finalmente, se mejoró la navegación hacia otros productos para ofrecer mayor facilidad.

![image](https://github.com/user-attachments/assets/0eaea883-e56c-4036-aebf-6e6707dc1b04)
