### ISSUE TITLE
botón de registro visible incluso cuando se está autenticado

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#22]
![image](https://github.com/user-attachments/assets/74230667-d1c3-41fb-a460-19db40e2da39)

Si estas autenticado no debe mostrar el botón de registro, y el mismo dirige al registro del usuario

**Comment by danferkz** [comment]
ya esta corregido.

![image](https://github.com/user-attachments/assets/360296e6-2ff6-4b1f-a5c2-b77f69ef5c33)
