### ISSUE TITLE
No funciona agregar usuario

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#24]
![image](https://github.com/user-attachments/assets/8f94eeed-7279-4efb-8b96-b686122ba4f6)
Además se pierde la barra de navegación

**Comment by danferkz** [comment]
esa vista ya fue corregida era para listar y ver todos los usuarios admin.

![image](https://github.com/user-attachments/assets/db698270-10f7-4d45-874f-6398b9a320d4)

detalle:

![image](https://github.com/user-attachments/assets/ac5befe9-0f58-4a1c-acb5-b3dbb3b94079)

crearlo:

![image](https://github.com/user-attachments/assets/67ccff3d-576c-4924-bf04-3e89655d9294)

eliminarlo:

![image](https://github.com/user-attachments/assets/7efc7f22-ede9-468d-aeb5-5dc02cc53742)
