### ISSUE TITLE
Textos en inglés y con faltas de ortografia

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#26]
![image](https://github.com/user-attachments/assets/69176d01-29ea-485e-bb0f-b271ffa7fd67)
Deberia ser Autenticar, Registrarse, Administrar si no desean incluir los acentos

**Comment by danferkz** [comment]
Corregido:

![image](https://github.com/user-attachments/assets/c1b20c9f-a9f6-4d0d-9627-5a5f3f207be0)
