### ISSUE TITLE
Footer fijo

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#27]
![image](https://github.com/user-attachments/assets/5a49d67d-1381-460f-a3ea-1f0e8f475662)
![image](https://github.com/user-attachments/assets/7218f249-d3f5-47c6-a9f4-99d99fbfcc97)

no permite visualizar los elementos correctamente, además siguen faltando las páginas de los enlaces del footter

**Comment by danferkz** [comment]
correccion:
![image](https://github.com/user-attachments/assets/a4bfab27-5689-4b7d-8689-75367b082a1d)
