### ISSUE TITLE
Error al terminar de realizar el pedido de un mueble

### ISSUE THREAD

**Issue by miguel-jaeger** [danferkz/SGC_sf#28]
![image](https://github.com/user-attachments/assets/447c7dd2-4eca-4951-b783-81d3f8e2db71)

![image](https://github.com/user-attachments/assets/78761eb3-21e8-45f7-b62c-f38435500509)

Da error al llegar al ultimo paso,

**Comment by danferkz** [comment]
ese error ocurre cuando el id del producto es el mismo. ya esta soluciona en forma logica por el lujo del uuario y reglas de validacion de la vista Delivey to Orden.

osea solo esa vista puede ser vista en una sola direccion.
![image](https://github.com/user-attachments/assets/f46eada2-513e-498f-8ad6-d53823cb2dd5)
